name: Publish Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
   runs-on: ubuntu-latest
   
   steps:
   - uses: actions/checkout@v2
     name: Set up Docker Buildx
   - uses: docker/setup-buildx-action@v2

   - name: docker build
     run: |
        docker build . -t bacayoco/html-server-image:latest
  
   - name: Login to ECR
     id: ecr
     uses: aws-actions/amazon-ecr-login@v1
     
     with:
       access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       region: us-east-1
   - name: push to ECR
     run: |
      docker tag docker-demo:latest 202082903014.dkr.ecr.us-east-1.amazonaws.com/docker-demo:latest
       docker push 202082903014.dkr.ecr.us-east-1.amazonaws.com/docker-demo:latest
