name: Publish Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
   runs-on: ubuntu-latest
   
   steps:
   - uses: actions/checkout@v2
     name: Set up Docker Buildx
   - uses: docker/setup-buildx-action@v2

   - name: docker build
     run: |
        docker build . -t docker-demo:latest
        
   - name: 'Get Login to AWS ECR'
     id: ecr-login
     uses: thalesvon/ecr-login@master
     env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_DEFAULT_OUTPUT: json
        AWS_REGION: us-east-1
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     with:
        args: 'get-login --no-include-email --region ${AWS_REGION}'
   - name: 'Docker Login'
     run: ${{ steps. ecr-login.outputs.login-string }}

   - name: push to ECR
     run: |
      docker tag docker-demo:latest 202082903014.dkr.ecr.us-east-1.amazonaws.com/docker-demo:latest
       docker push 202082903014.dkr.ecr.us-east-1.amazonaws.com/docker-demo:latest
