name: Publish Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
   runs-on: ubuntu-latest
   
   steps:
   - uses: actions/checkout@v2
     name: Set up Docker Buildx
   - uses: docker/setup-buildx-action@v2
     name: Login to Docker Hub
   - uses: docker/login-action@v2
     with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
   - name: docker build
     run: |
        docker build . -t bacayoco/html-server-image:latest
  
   - name: docker push
     run: |
      docker push bacayoco/html-server-image:latest
         
