name: Publish Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
   runs-on: ubuntu-latest
   
   steps:
   - uses: actions/checkout@v2
   - name: docker build
     run: |
        docker build . -t bacayoco/html-server-image:tagname
      
